<?php
/**
 * Author: Xavier Au
 * Date: 24/5/2017
 * Time: 1:34 PM
 */

namespace Anacreation\MultiAuth\Model;

use Anacreation\MultiAuth\Services\CacheManagementService;
use Fico7489\Laravel\Pivot\Traits\PivotEventTrait;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\Relation;

class AdminPermission extends Model
{
    use PivotEventTrait;

    protected $table = 'admin_permissions';

    protected static function boot() {
        parent::boot(); // TODO: Change the autogenerated stub

        static::pivotDetached(function (
            AdminPermission $permission, $relationName, $pivotIds
        ) {
            (new CacheManagementService())->forgetAdminPermissions($permission->roles);
        });
        static::pivotAttached(function (
            AdminPermission $permission, $relationName, $pivotIds
        ) {
            (new CacheManagementService())->forgetAdminPermissions($permission->roles);
        });
    }

    public function roles(): Relation {
        return $this->belongsToMany(AdminRole::class);
    }

}
