<?php
/**
 * Author: Xavier Au
 * Date: 24/5/2017
 * Time: 1:34 PM
 */

namespace Anacreation\MultiAuth\Model;


use Anacreation\MultiAuth\Services\CacheManagementService;
use Fico7489\Laravel\Pivot\Traits\PivotEventTrait;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\Relation;

class AdminRole extends Model
{
    use PivotEventTrait;

    protected $table = 'admin_roles';

    protected $fillable = [
        'label',
        'code'
    ];

    protected static function boot() {
        parent::boot(); // TODO: Change the autogenerated stub
        static::pivotDetached(function (
            AdminRole $role, $relationName, $pivotIds
        ) {
            (new CacheManagementService())->forgetAdminPermissions($role->users);
        });
        static::pivotAttached(function (
            AdminRole $role, $relationName, $pivotIds
        ) {
            (new CacheManagementService())->forgetAdminPermissions($role->users);
        });
    }

    public function users(): Relation {
        return $this->belongsToMany(Admin::class);
    }

    public function permissions(): Relation {
        return $this->belongsToMany(AdminPermission::class);
    }
}
